In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
df = pd.read_csv('train_set.csv')
df.shape

(315, 3240)

In [3]:
df.head()

,ID,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,...,Feature_3230,Feature_3231,Feature_3232,Feature_3233,Feature_3234,Feature_3235,Feature_3236,Feature_3237,Feature_3238,CLASS
0,ID_1,18281.541667,18432.0,9409.650391,0.514708,0.011300,0.045369,2.803803,0.356658,1.803803,...,382.968383,2214.0,1.0,136.625113,0.061710,0.0,28.154838,4.174959,0.061710,0
1,ID_2,20010.083333,20100.0,8303.049072,0.417707,0.014959,0.080294,2.338398,0.429532,1.338398,...,452.986164,2548.5,1.0,232.564022,0.090548,0.0,27.934229,3.931950,0.090548,1
2,ID_3,27260.125000,27437.0,12189.649414,0.447160,0.011428,0.046402,2.782842,0.359345,1.782842,...,419.781765,3400.0,1.0,233.593529,0.068704,0.0,27.904807,4.085035,0.068704,1
3,ID_4,41938.125000,42138.0,17866.433594,0.426019,0.009908,0.034878,3.060655,0.326727,2.060655,...,439.023968,5424.0,1.0,427.429572,0.078803,0.0,27.870588,4.011726,0.078803,0
4,ID_5,41274.125000,41439.0,14315.041992,0.346828,0.013596,0.065680,2.478506,0.403469,1.478506,...,485.209184,5096.0,1.0,726.731554,0.142608,0.0,28.846909,3.571352,0.142608,0

In [7]:
df.isnull().sum().sum()

2668

In [8]:
df.describe()

d:\After\torch\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
d:\After\torch\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Feature_1,Feature_2,Feature_3,Feature_4,Feature_5,Feature_6,Feature_7,Feature_8,Feature_9,Feature_10,...,Feature_3230,Feature_3231,Feature_3232,Feature_3233,Feature_3234,Feature_3235,Feature_3236,Feature_3237,Feature_3238,CLASS
count,315.000000,315.000000,315.000000,315.000000,315.000000,315.000000,315.000000,315.000000,315.000000,315.000000,...,315.000000,315.000000,315.0,315.000000,315.000000,315.0,315.000000,315.000000,315.000000,315.000000
mean,36401.611839,36558.978836,13421.797935,0.399783,0.013326,0.066770,2.572654,0.395949,1.572654,355.140036,...,458.273347,4580.805291,1.0,620.374167,0.112015,0.0,28.510670,3.792381,0.112015,0.393651
std,23979.228698,24006.711019,5229.346354,0.064272,0.002885,0.034442,0.305500,0.054492,0.305500,5460.014132,...,39.628050,2980.121623,0.0,1254.417871,0.043563,0.0,1.711272,0.257607,0.043563,0.489336
min,4601.166667,4646.000000,2420.351481,0.137726,0.008904,0.028169,1.684709,0.304269,0.684709,1.262551,...,309.374029,591.333333,1.0,45.791124,0.058477,0.0,16.430985,1.995746,0.058477,0.000000
25%,23287.562500,23443.500000,10245.704590,0.357646,0.011459,0.046652,2.403035,0.359990,1.403035,14.214779,...,432.298489,2881.000000,1.0,245.299821,0.083622,0.0,27.691774,3.655440,0.083622,0.000000
50%,34818.166667,35028.000000,13894.792969,0.394076,0.012477,0.055314,2.624547,0.381018,1.624547,24.110200,...,460.598280,4377.000000,1.0,424.561776,0.103960,0.0,28.424340,3.815115,0.103960,0.000000
75%,45575.708333,45750.000000,16633.839844,0.434799,0.014242,0.072065,2.777867,0.416141,1.777867,43.724701,...,484.566083,5769.000000,1.0,702.791528,0.131579,0.0,29.450389,3.963320,0.131579,1.000000
max,332120.750000,332379.000000,45741.601562,0.643473,0.025418,0.266032,3.286567,0.603905,2.286567,96940.788837,...,636.069588,40797.000000,1.0,20921.640194,0.512823,0.0,35.149153,4.271132,0.512823,1.000000

In [ ]:
string_columns = df.select_dtypes(include=['object', 'string']).columns.tolist()
print("String columns:", string_columns)
print("Number of string columns:", len(string_columns))

String columns: ['ID']
Number of string columns: 1

In [12]:
X = df.drop(columns=['CLASS', 'ID'])
y = df['CLASS']

In [ ]:
# Check for infinite values
has_inf = X.map(lambda x: np.isinf(x) if np.issubdtype(type(x), np.number) else False).any()
inf_columns = has_inf[has_inf].index.tolist()
print("Columns with infinite values:", inf_columns)

# Check for very large values
large_values = X.select_dtypes(include=[np.number]).abs() > np.finfo(np.float64).max
large_columns = large_values.any()[large_values.any()].index.tolist()
print("Columns with values too large for float64:", large_columns)

Columns with infinite values: ['Feature_72', 'Feature_90']
Columns with values too large for float64: ['Feature_72', 'Feature_90']

In [17]:
# replacing the infinite values with NaN
X = X.replace([np.inf, -np.inf], np.nan)

# Check for infinite values
has_inf = X.map(lambda x: np.isinf(x) if np.issubdtype(type(x), np.number) else False).any()
inf_columns = has_inf[has_inf].index.tolist()
print("Columns with infinite values:", inf_columns)

# Check for very large values
large_values = X.select_dtypes(include=[np.number]).abs() > np.finfo(np.float64).max
large_columns = large_values.any()[large_values.any()].index.tolist()
print("Columns with values too large for float64:", large_columns)

Columns with infinite values: []
Columns with values too large for float64: []